language: node_js
node_js:
  - "12.2"
cache:
  - node_modules
install:
  - npm install
before_script:
  - npm run build
script:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  keep-history: true
  local-dir: .site
  committer-from-gh: true
  fqdn: dandart.co.uk
  on:
    branch: master